### ISSUE TITLE
Python test suite

### ISSUE THREAD

**Issue by guycipher** [tidesdb/tidesdb-python#4]
Unit testing classes accordingly.

**Comment by imprvhub** [comment]
hey @guycipher can i be assigned to this? I would like to contribute!.

**Comment by guycipher** [comment]
**Creating a column family**

In order to store data in TidesDB you need a column family. This is by design.

You pass

the database you want to create the column family in. Must be open
the name of the column family
memtable flush threshold in bytes. Example below is 128MB
skip list max level. Example below is 12
skip list probability. Example below is 0.24
whether column family sstable data is compressed
the compression algorithim to use [TDB_NO_COMPRESSION, TDB_COMPRESS_SNAPPY, TDB_COMPRESS_LZ4, TDB_COMPRESS_ZSTD]
whether to use bloom filters
what data structure to use for the memtable [TDB_MEMTABLE_SKIP_LIST, TDB_MEMTABLE_HASH_TABLE]

/* create a column family with no compression and no bloom filters (slower reads) */
tidesdb_err_t *e = tidesdb_create_column_family(tdb, "your_column_family", (1024 * 1024) * 128, 12, 0.24f, false, TDB_NO_COMPRESSION, false, TDB_MEMTABLE_SKIP_LIST);
if (e != NULL)
{
    /* handle error */
    tidesdb_err_free(e);
}
Using Snappy compression and bloom filters for column family sstables

/* create a column family with compression and bloom filter (the bloom filter provides fast read speed) */
tidesdb_err_t *e = tidesdb_create_column_family(tdb, "your_column_family", (1024 * 1024) * 128, 12, 0.24f, true, TDB_COMPRESS_SNAPPY, true);
if (e != NULL)
{
    /* handle error */
    tidesdb_err_free(e);
}

**Comment by guycipher** [comment]
So in this regard the python package will need to be modified before writing the initial tests.  I can do this if you require me to @imprvhub .

**Comment by guycipher** [comment]
I’ve assigned you.  If you need any assistance do let me know.  I am working on a discord server for TidesDB but yeah.  Thank you @imprvhub very good stuff!!
